# Generated by Django 6.0.2 on 2026-02-09 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_is_host_hostprofile_hostreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostprofile",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
