# Generated by Django 6.0.2 on 2026-02-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_hostprofile_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostprofile",
            old_name="is_active",
            new_name="is_host",
        ),
    ]
