# Generated by Django 6.0.2 on 2026-02-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.ImageField(upload_to="listings/%Y/%m/%d/"),
        ),
    ]
